### ISSUE TITLE
Can't handle multiple output

### ISSUE THREAD

**Issue by AchalaSB** [wasmerio/go-ext-wasm#102]
Hi,
Trying to return multiple result using wasmer. Here is sample code
```
#[no_mangle]
pub extern fn test(x: i32, y: i32, z: i32) -> (i32, i32, i32) {
    (x, y, z) 
}

// try this since test function returning 0
#[no_mangle]
pub extern fn sub_main() -> (i32, i32, i32) {
   test(5, 1, 3)
}

fn main() {}
```
When I try to call `test` function from wasmer  
```
sum := instance.Exports["test"] 
result, _ := sum(4, 5, 3)
```
It is returning result as 0.  And if I call `sub_main` function
```
sum := instance.Exports["sub_main"] 
result, _ := sum()
```
It is returning error
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4a2f15]

goroutine 1 [running]:
main.main()
        /go-ext-plugin/wasmer-ext.go:21 +0x125
exit status 2
```

**Comment by AdamSLevy** [comment]
The web assembly specification currently does not allow multiple return values from functions.

**Comment by Hywan** [comment]
That is _partially_ true. The Multi-value proposal has reached [Phase 3: Implementation Phase](https://github.com/WebAssembly/proposals/labels/Phase%203%3A%20Implementation%20Phase). But Wasmer isn't supporting it for the moment. We are working on it though.

**Comment by Hywan** [comment]
@AchalaSB Can you [re-open the issue on wasmerio/wasmer](https://github.com/wasmerio/wasmer/issues/new?assignees=&labels=%F0%9F%8E%89+enhancement&template=---feature-request.md&title=) please, so that we can prioritize the implementation? Thanks!

Closing this issue for now.

**Comment by clarkmcc** [comment]
I've looked through docs, issues, and examples and can't seem to find anything on working with multiple return values. Can someone point me in the right direction?
