### ISSUE TITLE
example imported_function.wasm    could not determine kind of name for C.sum

### ISSUE THREAD

**Issue by tx991020** [wasmerio/go-ext-wasm#105]
```go
func sum(context unsafe.Pointer, x int32, y int32) int32 {
	return x + y
}

func Test3()  {
	bytes, err := wasm1.ReadBytes("/Users/andy/Downloads/imported_function.wasm")
	if err != nil {
		fmt.Println(err)
	}
	imports, err := wasm1.NewImports().Append("sum", sum, C.sum)
	if err != nil {
		fmt.Println(err)
	}

	instance, _ := wasm1.NewInstanceWithImports(bytes, imports)

	// Close the WebAssembly instance later.
	defer instance.Close()

	// Gets the `add1` exported function from the WebAssembly instance.
	add1 := instance.Exports["add1"]

	// Calls that exported function.
	// As a reminder: `add1` is defined as `fn add1(x: i32, y: i32) -> i32 { sum(x, y) + 1 }`
	result, _ := add1(1, 2)

	// Should output 4 (= 1 + 2 + 1).
	fmt.Println(result)
}
```

could not determine kind of name for C.sum

<hr />

Edit from @Hywan: Markup.

**Comment by Hywan** [comment]
Hello @tx991020,

You need to setup cgo, and tells cgo to export the `sum` function, such as:

```go
// #include <stdio.h>
//
// extern int sum(void *context, int x, int y);
import "C"

//export sum
func sum(context unsafe.Pointer, x int32, y int32) int32 {
    return x + y
}
```

Please refer to the tests to get more insights, https://github.com/wasmerio/go-ext-wasm/blob/master/wasmer/test/imports.go.

**Comment by tx991020** [comment]
before I mentioned this bug，I have  already  import import "C".     my IDE is mac

**Comment by Hywan** [comment]
Do you have the `//export sum` comment before the `sum` function?

**Comment by tx991020** [comment]
package main

import (
	"C"

	"fmt"
	"unsafe"

	wasm "github.com/wasmerio/go-ext-wasm/wasmer"
)

func sum(context unsafe.Pointer, x int32, y int32) int32 {
	return x + y
}
func main() {
	imports, _ := wasm.NewImports().Append("sum", sum, C.sum)

	bytes, _ := wasm.ReadBytes("/Users/andy/Downloads/imported_function.wasm")
	instance, _ := wasm.NewInstanceWithImports(bytes, imports)

	// Close the WebAssembly instance later.
	defer instance.Close()

	// Gets the `add1` exported function from the WebAssembly instance.
	add1 := instance.Exports["add1"]

	// Calls that exported function.
	// As a reminder: `add1` is defined as `fn add1(x: i32, y: i32) -> i32 { sum(x, y) + 1 }`
	result, _ := add1(1, 2)

	// Should output 4 (= 1 + 2 + 1).
	fmt.Println(result)

}


# goenc/wasm
./main.go:16:53: could not determine kind of name for C.sum

**Comment by tx991020** [comment]
I think this is a bug, but I didn't get the correct solution, I finally chose  github.com/go-interpreter/wagon/wasm。

**Comment by tx991020** [comment]
I am not a golang beginner, please give me some useful answers

**Comment by Hywan** [comment]
You need to add a “special comment/instruction” before declaring the `sum` function:

```go
//export sum
func sum(…) { … }
```

The special syntax `//export <name>` is used by cgo to link Go and C together.

**Comment by Hywan** [comment]
Check https://golang.org/cmd/cgo/#hdr-C_references_to_Go to learn more.

**Comment by Hywan** [comment]
Also, note that https://github.com/wasmerio/go-ext-wasm/issues/105#issuecomment-571272162 _is_ the answer to your problem.

**Comment by tx991020** [comment]
that #105 (comment) is the answer
