### ISSUE TITLE
How to pass variadic function instead of value?

### ISSUE THREAD

**Issue by AchalaSB** [wasmerio/go-ext-wasm#112]
How can we pass `n` variables to `sum()` function instead of separate values
```
package main

import (
	"fmt"
	wasm "github.com/wasmerio/go-ext-wasm/wasmer"

)
func main() {
	
	fmt.Println("result is", test(3, 4))
	fmt.Println("result is", test(3, 4, 5))

}

func test(input1, input2, input3 int) int{
	bytes, _ := wasm.ReadBytes("test.wasm")
	
	// Instantiates the WebAssembly module.
	instance, _ := wasm.NewInstance(bytes)
	defer instance.Close()

	// Gets the `sum` exported function from the WebAssembly instance.
	//sum := instance.Exports["sum"]
	sum2 := instance.Exports["sum2"]

	// Calls that exported function with Go standard values. The WebAssembly
	// types are inferred and values are casted automatically.
	
	// result, _ := sum(3, 4) // pass variadic function value
       // result, _ := sum2(input1, input2, input3)) // works fine

	fmt.Println(result)   
	return result

}
```
how to pass instead of this
```
func test(input ...int)int {
      // body goes here

      // pass values in generic way
	result, _ := sum(input) 
       fmt.Println(result)   
	return result

}
```

Thanks

**Comment by Hywan** [comment]
It is not possible to pass an array of values. Variadic parameters aren't supported in WebAssembly. However, you can try `sum(input...)`.

**Comment by AchalaSB** [comment]
Tried, `sum(input...)` 
getting error `cannot use input (variable of type []int) as []interface{} value in argument to output`

**Comment by Hywan** [comment]
I think you should cast `[]int` to `[]interface{}`, and then unpack it into `sum`.

**Comment by AchalaSB** [comment]
@Hywan can we pass array of variables?
```
package main
import (
    "fmt"
    wasm "github.com/wasmerio/go-ext-wasm/wasmer"
)
func main() {
   	val := []int{3, 2}
	test(val)
}
func test(input []int) int{
    bytes, _ := wasm.ReadBytes("test.wasm")
    instance, _ := wasm.NewInstance(bytes)
    defer instance.Close()
    // Gets the `sum` exported function from the WebAssembly instance.
    sum := instance.Exports["sum"]
    // result, _ := sum(input) // pass array of values
    fmt.Println(result)   
    return result
}
```
It returning as 0. Is this feature also not supported?

**Comment by AdamSLevy** [comment]
check your error. You are getting zero because an error is occurring that you aren't printing in your example. 

The main issue on the Go side of things is that you are passing the slice directly into the `sum` closure. You want to do this instead: `sum(input...)` which will pass the slice of ints in variadically. In other words it is akin to doing `sum(input[0], input[1], ..., input[len(input)-1])`.

However, I highly doubt this will work for any slice of ints because the underlying Wasm function that implements `sum` cannot be variadic, as there is no variadic specification in Wasm currently.

**Comment by AchalaSB** [comment]
When I pass variadic function like this `func test(input ...interface{})` and pass it to `sum(input...)` it works. 
But i was figuring out the way to pass complete array at a time if i don't know the array length or it is automated by some other function. ( passing as slices will work `test(val[0], test[1]`)

**Comment by rusenask** [comment]
@AchalaSB have you considered encoding the array into protobuf or json and then just passing it normally as offset and length? that makes life easier :)

**Comment by AchalaSB** [comment]
yes. In my use case have considered encoded json array. Actually those inputs i'm reading from json file. That is why I said i may not know the length. 

Anyway variadic function works better. will follow that for now

**Comment by Hywan** [comment]
Then, I'm closing this issue :-). Feel free to re-open if you have any more questions!
