### ISSUE TITLE
LICENSE not recognized by pkg.go.dev

### ISSUE THREAD

**Issue by szabba** [wasmerio/go-ext-wasm#121]
### Describe the bug

The automatic license detection done by pkg.go.dev does not recognize that the library is under the MIT license.
This is important as godoc.org is being phased out due to legal issues.

### Steps to reproduce

1. Visit https://pkg.go.dev/github.com/wasmerio/go-ext-wasm/wasmer?tab=doc

### Expected behavior

The documentation for the package should be visible for people visiting https://pkg.go.dev/github.com/wasmerio/go-ext-wasm/wasmer?tab=doc .

### Actual behavior

The documentation is not visible.
A message explaining that the license could not be recognized is shown instead.

![image](https://user-images.githubusercontent.com/820119/75702890-a3323000-5cb6-11ea-8da8-00aa2f60930e.png)
![image](https://user-images.githubusercontent.com/820119/75702911-b2b17900-5cb6-11ea-8890-3e28a6e637fd.png)

### Additional context

It is my understanding that placing the license text verbatim in the `LICENSE` file would resolve the issue.

**Comment by syrusakbary** [comment]
Now docs are visible again:
https://pkg.go.dev/github.com/wasmerio/go-ext-wasm/wasmer?tab=doc

Thanks for the ping @szabba

**Comment by Hywan** [comment]
Haha, I was workong on this yesterday :-D.
