### ISSUE TITLE
Sending a nil or emty []byte to Validate will panic

### ISSUE THREAD

**Issue by diegobes** [wasmerio/go-ext-wasm#123]
Thanks for the bug report!

### Describe the bug

in function:
```
wasmer/module.go
// Validate validates a sequence of bytes that is supposed to represent a valid
// WebAssembly module.
func Validate(bytes []byte) bool {
	return true == cWasmerValidate((*cUchar)(unsafe.Pointer(&bytes[0])), cUint(len(bytes)))
}
```
if bytes is nil &[bytes[0] will make the app crash.

Something like:
```
if bytes == nil || len(bytes) == 0 {
   return false
}
```
Will make it safer
### Steps to reproduce

Sending a nil to the Validate function will panic with the following message:

`panic: runtime error: index out of range [0] with length 0`

**Comment by Hywan** [comment]
Thanks for the patch. Discussion happens in #124.
