### ISSUE TITLE
Actually use WASM generated from Go code

### ISSUE THREAD

**Issue by mpl** [wasmerio/go-ext-wasm#130]
### Summary

How to import and use WASM that was generated from Go code?

### Additional details

Given that the examples in the README are somewhat a bit more convoluted, with some rust bits in between, I am still unsure whether this library is supposed to enable the use of WASM code that was actually generated from (pure) Go.

For example, if I have:

```
package main

import "fmt"

func Hello() {
	fmt.Println("Hello, WebAssembly!")
}

func main() {
	fmt.Println("Hello, WebAssembly!")
}
```

that I build as:

`GOOS=js GOARCH=wasm go build -o ./hello.wasm`

and that I want to use it in another program, such as:

```
package main

import (
	"log"

	"github.com/wasmerio/go-ext-wasm/wasmer"
)

func main() {
	// Reads the WebAssembly module as bytes.
	bytes, err := wasmer.ReadBytes("./hello.wasm")
	if err != nil {
		log.Fatal(err)
	}

	// Instantiates the WebAssembly module.
	instance, err := wasmer.NewInstance(bytes)
	if err != nil {
		log.Fatal(err)
	}
	defer instance.Close()

	hello := instance.Exports["Hello"]
	hello()
}
```

then I get:

```
go run ./main.go
2020/04/08 14:14:32 Failed to instantiate the module:
    21 link errors: (1 of 21) Import not found, namespace: go, name: debug (2 of 21) Import not found, namespace: go, name: runtime.resetMemoryDataView (3 of 21) Import not found, namespace: go, name: runtime.wasmExit (4 of 21) Import not found, namespace: go, name: runtime.wasmWrite (5 of 21) Import not found, namespace: go, name: runtime.nanotime1 (6 of 21) Import not found, namespace: go, name: runtime.walltime1 (7 of 21) Import not found, namespace: go, name: runtime.scheduleTimeoutEvent (8 of 21) Import not found, namespace: go, name: runtime.clearTimeoutEvent (9 of 21) Import not found, namespace: go, name: runtime.getRandomData (10 of 21) Import not found, namespace: go, name: syscall/js.finalizeRef (11 of 21) Import not found, namespace: go, name: syscall/js.stringVal (12 of 21) Import not found, namespace: go, name: syscall/js.valueGet (13 of 21) Import not found, namespace: go, name: syscall/js.valueSet (14 of 21) Import not found, namespace: go, name: syscall/js.valueIndex (15 of 21) Import not found, namespace: go, name: syscall/js.valueSetIndex (16 of 21) Import not found, namespace: go, name: syscall/js.valueCall (17 of 21) Import not found, namespace: go, name: syscall/js.valueNew (18 of 21) Import not found, namespace: go, name: syscall/js.valueLength (19 of 21) Import not found, namespace: go, name: syscall/js.valuePrepareString (20 of 21) Import not found, namespace: go, name: syscall/js.valueLoadString (21 of 21) Import not found, namespace: go, name: syscall/js.copyBytesToJS
exit status 1
```

Is this expected? If yes, is there a way to achieve what I'm trying to do?
From what I gathered in the official documentation (https://github.com/golang/go/wiki/WebAssembly) it seemed to me that WASM code that was generated from Go needed a javascript environment to run so I wouldn't expect go-ext-wasm to be able to handle it without embedding Node.js or something like that, but maybe I misunderstood?

**Comment by mpl** [comment]
I see now that my question is probably a duplicate of #87 , and that the answer is probably "no, I can't achieve that with go-ext-wasm".
Unless you made any progress on that matter since then?

**Comment by rusenask** [comment]
in theory you could try using this branch https://github.com/wasmerio/go-ext-wasm/pull/95 but even after adding those missing imports I encountered some other issues :)

**Comment by mpl** [comment]
FYI, with tinygo, the error is slightly different:

```
2020/04/08 15:40:44 Failed to instantiate the module:
    11 link errors: (1 of 11) Import not found, namespace: wasi_unstable, name: fd_write (2 of 11) Import not found, namespace: env, name: syscall/js.valueLength (3 of 11) Import not found, namespace: env, name: syscall/js.valueCall (4 of 11) Import not found, namespace: env, name: syscall/js.valueIndex (5 of 11) Import not found, namespace: env, name: syscall/js.valueGet (6 of 11) Import not found, namespace: env, name: syscall/js.valueNew (7 of 11) Import not found, namespace: env, name: syscall/js.valueSet (8 of 11) Import not found, namespace: env, name: syscall/js.valueSetIndex (9 of 11) Import not found, namespace: env, name: syscall/js.stringVal (10 of 11) Import not found, namespace: env, name: syscall/js.valuePrepareString (11 of 11) Import not found, namespace: env, name: syscall/js.valueLoadString
exit status 1
```

**Comment by mpl** [comment]
@rusenask Same. Even with the branch and tinygo, for now I'm stuck with errors (or warnings?) such as:

```
$ tinygo run ./main.go
# github.com/mpl/go-ext-wasm/wasmexec
../../../../../../../Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdlib.h:134:25: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)
../../go-ext-wasm/wasmexec/wasmexec.go:6:10: note: in file included from ../../go-ext-wasm/wasmexec/wasmexec.go!cgo.c:2:
../../../../../../../Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdlib.h:134:25: note: insert '_Nullable' if the pointer may be null
../../../../../../../Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdlib.h:134:25: note: insert '_Nonnull' if the pointer should never be null
../../../../../../../Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdlib.h:135:22: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)
../../../../../../../Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdlib.h:135:22: note: insert '_Nullable' if the pointer may be null
....
```

and FWIW, I did set
`CGO_CPPFLAGS=-Wno-error -Wno-nullability-completeness -Wno-expansion-to-defined`

**Comment by danlaine** [comment]
I would also love this functionality!

**Comment by Hywan** [comment]
#95 isn't finished yet. `go` Wasm API isn't stable yet, and is changing a lot. We are not rushing on that part. Also, checks https://github.com/vedhavyas/go-wasm.

**Comment by mpl** [comment]
@Hywan yes, I forgot to give any update here, but I found out about https://github.com/vedhavyas/go-wasm in the meantime, and so far it seems to be a good enough work-around for me (without even using the #95 branch).

**Comment by mpl** [comment]
Just fyi, and as an update about https://github.com/vedhavyas/go-wasm , I don't think it actually is usable atm. One way or another, if one's program is more than a trivial helloworld, it seems one ends up eventually hitting a panic of this kind:

```
fatal error: exitsyscall: syscall frame is no longer valid

goroutine 15 [running, locked to thread]:
runtime.throw(0x434b193, 0x2d)
	/Users/mpl/go1/src/runtime/panic.go:774 +0x72 fp=0xc000056ae8 sp=0xc000056ab8 pc=0x40307a2
runtime.exitsyscall()
	/Users/mpl/go1/src/runtime/proc.go:2957 +0x27d fp=0xc000056b18 sp=0xc000056ae8 pc=0x40393dd
runtime.cgocall(0x4293a20, 0xc000056b80, 0x2c00000000)
	/Users/mpl/go1/src/runtime/cgocall.go:138 +0x9e fp=0xc000056b50 sp=0xc000056b18 pc=0x4004eee
github.com/wasmerio/go-ext-wasm/wasmer._Cfunc_wasmer_instance_call(0x4e00fb0, 0x4e01160, 0xc00000e340, 0x0, 0xc00000e360, 0x0, 0x2)
	_cgo_gotypes.go:744 +0x4d fp=0xc000056b80 sp=0xc000056b50 pc=0x4286bbd
github.com/wasmerio/go-ext-wasm/wasmer.cWasmerInstanceCall(...)
	/Users/mpl/src/github.com/wasmerio/go-ext-wasm/wasmer/bridge.go:503
github.com/wasmerio/go-ext-wasm/wasmer.getExportsFromInstance.func2(0x0, 0x0, 0x0, 0x6, 0xc0000ecb20, 0x4012f4a, 0xc000056d60)
	/Users/mpl/src/github.com/wasmerio/go-ext-wasm/wasmer/instance.go:365 +0x1fe fp=0xc000056cf8 sp=0xc000056b80 pc=0x4287b9e
github.com/vedhavyas/go-wasm.(*Bridge).resume(...)
	/Users/mpl/pkg/mod/github.com/vedhavyas/go-wasm@v0.0.0-20200105170157-8d9eb0eae927/bridge.go:452
github.com/vedhavyas/go-wasm.(*Bridge).makeFuncWrapper(0xc0000e0aa0, 0x42c60a0, 0xc0000184c8, 0x42b8ec0, 0xc00000e3c0, 0xc007ce3c20, 0x0, 0x40bb834, 0xc000092000, 0xc004440080)
	/Users/mpl/pkg/mod/github.com/vedhavyas/go-wasm@v0.0.0-20200105170157-8d9eb0eae927/bridge.go:469 +0x220 fp=0xc000056d50 sp=0xc000056cf8 pc=0x428d2f0
github.com/vedhavyas/go-wasm.(*Bridge).CallFunc(0xc0000e0aa0, 0x433db0e, 0x3, 0xc007ca1c90, 0x1, 0x1, 0x8, 0xc007cdf708, 0x0, 0x0)
	/Users/mpl/pkg/mod/github.com/vedhavyas/go-wasm@v0.0.0-20200105170157-8d9eb0eae927/bridge.go:486 +0x1d0 fp=0xc000056de8 sp=0xc000056d50 pc=0x428d600
```

which happens when (not systematically of course) the "resume" function registered in the Exported functions is called. This behaviour also seems to be racy, as I can defer it (sometimes even long enough for it to never happen), just by sprinkling some println here and there.

It is also very easily reproducible, simply by using the example at https://github.com/vedhavyas/go-wasm/blob/master/examples/function-wasm/main.go , and removing the blocking channel at https://github.com/vedhavyas/go-wasm/blob/master/examples/function-wasm/main.go#L60 (i.e. by letting the main function return).

**Comment by Hywan** [comment]
Please, open an issue on `go-wasm`'s repository, ping @vedhavyas.

It is important to understand that Go' support for Wasm is pretty experimental, and their WASI support is highly unstable for the moment. It is progressing though.

**Comment by mpl** [comment]
> Please, open an issue on `go-wasm`'s repository, ping @vedhavyas.

yeah, I should. I was waiting to see if I had missed something obvious while using go-wasm, but no luck so far.

> It is important to understand that Go' support for Wasm is pretty experimental, and their WASI support is highly unstable for the moment. It is progressing though.

Sure, I know. For example I've noticed go-wasm does not support Go 1.14, because they changed a bunch of things in the javascript Host functions compared to Go 1.13: https://github.com/vedhavyas/go-wasm/issues/6

I'm not sure why you closed the issue though. At the end of the day I think it's still relevant to the use of go-ext-wasm.

**Comment by mpl** [comment]
Ah nevermind, since the issue was a question to begin with, and not a bug report, I suppose it should indeed be closed, as the question is "answered".
