### ISSUE TITLE
Allow imports to use functions from structs / Multi-threading

### ISSUE THREAD

**Issue by pkedy** [wasmerio/go-ext-wasm#23]
### Motivation

I am testing several WebAssembly runtimes [here](https://github.com/pkedy/wasmtest).  In my use case I will be sending and receiving JSON payloads to a function in a multi-threaded host.  Currently `Imports.Append` can only use exported function pointers which are global.  Unless there is some meaning to `context unsafe.Pointer`, I cannot encapsulate the input/output JSON in a struct per `Instance`.

Also, It would also be nice if compilation and execution were separate steps.  In a multi-threaded host, this would mean that the cost of compilation is only incurred once.

### Proposed solution

This might not be possible with CGO but somehow use the `implementation interface{}` parameter of `Imports.Append` as the execution target.  Currently it is only used to read the parameters and return type.  Another approach could be to pass the `Instance` pointer as `context` and include a `UserData` field so that you can cast and delegate to a struct implementation.

For separation of compilation and execution, there might be a `func wasm.NewModuleWithImports(code []byte, imports *Imports) *Module` function that returns the compiled module instructions, etc.  Then `module.NewInstance` would return a single VM with its own memory, etc.

### Additional context

General question: How does the one use the `context unsafe.Pointer` parameter?  I've tried casting it to `*Instance` and `*Memory`.  Both attempts ended poorly (core dump).  A sample in the README would be super helpful.

**Comment by hleb-albau** [comment]
Very exited to use structs with wasmerio

**Comment by Hywan** [comment]
Thanks for your proposal. I read multiple requests:

1. Module compilation and caching,
2. Define imported function without `cgo`,
3. Make `context unsafe.Pointer` no longer opaque in imported functions signature,
4. Define instance context “user data”.

So, about 1, see https://github.com/wasmerio/go-ext-wasm/issues/27.
About 2, imported function must rely on `cgo` so far. I don't see any other way to do that with the Wasm runtime.
About 3, see #26.
About 4, if you're talking about a way to pass data from within an imported function to the outside, I'm working on an “instance context data” API, see https://github.com/wasmerio/go-ext-wasm/issues/28.

**Comment by Hywan** [comment]
I think all the questions have been addressed. Closing the issue. Feel free to speak if I miss one point and I'll re-open it. Thanks!
