### ISSUE TITLE
Configure the namespace of the imports functions

### ISSUE THREAD

**Issue by YaronWittenstein** [wasmerio/go-ext-wasm#25]
Currently, the `NewImports()` hard-codes the import namespace as `env`.

If we compile a Rust program to WASM file, then the Rust compiler also hardcodes the
import namespace as `env` too (so the current wasmer go binding the Rust wasm output files play well together)

However, if we patch a wasm file import namespace to something else (different than `env`), then we won't be able to use it via the golang wasmer binding

### Proposed solution
Instead of 
```go
imports, _ := wasm.NewImports().Append("sum", sum, C.sum)
```

Have this API:
```go
imports, _ := wasm.NewImports().Append("my_namespace",  "sum", sum, C.sum)
```

Thank you! @Hywan  :)

**Comment by Hywan** [comment]
Thanks for the proposal!

What do you think about this API:

```go
wasm.NewImports().
    Namespace("env").
        Append("sum", sum, C.sum).
        Append("f", f, C.f).
    Namespace("wasi").
        Append("log", log, C.log)
```

Would you like it? It's more like a tree. `Append` uses the last defined `Namespace`.

**Comment by YaronWittenstein** [comment]
@Hywan that's even better, (I guess the default namepace will be `env`)

**Comment by Hywan** [comment]
Correct, `env` will be the default namespace.
