### ISSUE TITLE
Gas calculation

### ISSUE THREAD

**Issue by Wondertan** [wasmerio/go-ext-wasm#39]
### Summary

Is it possible to count Gas per operation like in Ethereum or perlin-life using your library to create Smart Contracts?

**Comment by Hywan** [comment]
Thanks for the question!

Metering is being implemented in the runtime, see https://github.com/wasmerio/wasmer/pull/450. Only the Singlepass backend supports it yet, but it's coming in Cranelift (which is the backend used by the Go library).

**Comment by Wondertan** [comment]
Thanks!
