### ISSUE TITLE
NewInstanceWithImports does not return helpful error when there is a mismatch

### ISSUE THREAD

**Issue by fproulx-eoscanada** [wasmerio/go-ext-wasm#41]
`NewInstanceWithImports` calls out to `cWasmerInstantiate` and that only returns a simple error.

### Motivation

To determine which imports are expected we should get better error feedback.

### Proposed solution

Return more extensive error details with list of missing imports.

**Comment by Hywan** [comment]
You're right! #42 addresses your request, thanks for the proposal!
