### ISSUE TITLE
Panic when attempting to execute function that doesn't exist in wasm

### ISSUE THREAD

**Issue by noot** [wasmerio/go-ext-wasm#48]
### Describe the bug

When calling a function that doesn't exist in the wasm module, a `panic: runtime error: invalid memory address or nil pointer dereference [recovered]` occurs.

### Steps to reproduce

```
package main

import (
	"fmt"
	wasm "github.com/wasmerio/go-ext-wasm/wasmer"
)

func main() {
	bytes, _ := wasm.ReadBytes("mymodule.wasm")
	instance, _ := wasm.NewInstance(bytes)
	defer instance.Close()
	myfunc := instance.Exports["nonexistentfunction"]
	res, _ := myfunc()
        fmt.Print(res)
}
```

### Expected behavior
Either, we should not be allowed to get an instance.Export that doesn't exist, or when trying to call the nonexistent function there should be an error saying it doesn't exist.

### Actual behavior

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8458f2]

```
at the line `res, _ := myfunc()`

**Comment by Hywan** [comment]
Thanks for asking. The exports API is Go idiomatic regarding map access, thus you can write:

```go
myfunc, ok := instance.Exports["nonexistentfunction"]

if !ok {
    // function doesn't exist
}
```

To learn more, check https://blog.golang.org/go-maps-in-action.
