### ISSUE TITLE
Memory growth does not appear to be supported in Go

### ISSUE THREAD

**Issue by fproulx-eoscanada** [wasmerio/go-ext-wasm#52]
### Motivation

Right now in Go, we get a Memory, but it's not clear how many pages it gets and there is no way to manage (grow) it dynamically.

### Proposed solution

Rust lib has `wasmer_memory_grow` which is already linked, but not exposed in Go binding.

**Comment by Hywan** [comment]
Yup, we can add it. PR are welcome, or wait few days I make it :-).
