### ISSUE TITLE
IDL RPC standard yet ?

### ISSUE THREAD

**Issue by ghost** [wasmerio/go-ext-wasm#53]
### Summary

Is there a standard yet ? For example many use protobufs as an IDL to describe and code generate the stubs to allow inter process communication.
We need something like this for wasi I think and I have not found it 

### Additional details

Have Mozilla specified this yet ?

The idea is that if party A writes in python and party B writes in golang, then how can the golang code call / RPC the python code when everyone is compiling to WASM.

Also you have the other aspect of message queues where your calling a wasi on another server and you have no idea if they are on the network or partitioned. This is sort of another issue but related.

**Comment by Hywan** [comment]
I think you want to take a look at Web IDL Bindings, https://github.com/wasmerio/wasmer/pull/489. It's a giant draft. Many WebAssembly actors are working on it, incl. Google, Mozilla, and us (Wasmer).

**Comment by Hywan** [comment]
Duplicated with #75. Closing this one.
