### ISSUE TITLE
unable to handle `f32` types.

### ISSUE THREAD

**Issue by AchalaSB** [wasmerio/go-ext-wasm#76]
Hi, I couldn't handle `f32` types.
Here is the code
```
#[no_mangle] 
pub extern fn sum(x:f32, y:f32) -> f32 {
x + y
}
```
I'm getting result as `0` when I pass it in go-wasmer
Thnaks

**Comment by Hywan** [comment]
Can I see you Go code please?

**Comment by AchalaSB** [comment]
Here is the go code.same as in example
```
package main

import (
	"fmt"
	wasm "github.com/wasmerio/go-ext-wasm/wasmer"
)

func main() {
	// Reads the WebAssembly module as bytes.
	bytes, _ := wasm.ReadBytes("simple.wasm")
	
	// Instantiates the WebAssembly module.
	instance, _ := wasm.NewInstance(bytes)
	defer instance.Close()

	// Gets the `sum` exported function from the WebAssembly instance.
	sum := instance.Exports["sum"]

	// Calls that exported function with Go standard values. The WebAssembly
	// types are inferred and values are casted automatically.
	result, _ := sum(5.2, 4.1)

	fmt.Println(result) 
}
```

**Comment by Hywan** [comment]
Go floats are by default of type `float64`. You must precise the type by writing:

```go
result, _ := sum(float32(5.2), float32(4.1))
```

See this test case to learn more https://github.com/wasmerio/go-ext-wasm/blob/e0517c02f18efb99cd29720fdb9cfbfbe3de650b/wasmer/test/instance_test.go#L181-L196.

**Comment by AchalaSB** [comment]
Thanks @Hywan
Its working fine. My bad was trying it as default since f64 was taking by default.
