### ISSUE TITLE
Is go-wasmer can handle C codes?

### ISSUE THREAD

**Issue by AchalaSB** [wasmerio/go-ext-wasm#77]
Using go-wasmer we were able to handle Rust code by calling extern function.

can we do same for C codes?
is it compatible now?

If yes. How can we call C code as an extern function?

**Comment by Hywan** [comment]
If your C code is compiled to WebAssembly, yes, it will work!

**Comment by AchalaSB** [comment]
Yea, we can compile C code to wasm. 
So again wasmer requires the C code as extern function only?

Is there any examples, go-wasmer handles C code?

**Comment by Hywan** [comment]
So far, a useful tool is https://emscripten.org/. More to come in few days :-).

**Comment by AchalaSB** [comment]
Using emscripten we can compile. but that can't be use in go-wasmer. 
We can compile using `WASI` if that supports in go-wasmer its good to go. (even for Rust)

I see go-wasmer is working on WASI. Waiting for WASI support

**Comment by Hywan** [comment]
*Few days later*

We've released `wasienv`, check it out https://medium.com/wasmer/wasienv-wasi-development-workflow-for-humans-1811d9a50345 :-)

**Comment by AchalaSB** [comment]
This looks good to me. But my feature request is to handle wasm bytecode(from C/C++ code) in go module.

This wasienv is usable in only in wasmer if I'm not wrong

**Comment by Hywan** [comment]
wasienv helps to compile a C/C++ program to Wasm (with WASI support), and then you can use this Wasm module anywhere, incl. this project.

**Comment by AchalaSB** [comment]
Thanks will try with go module.
Is there any specific way to write code in C/C++ like in Rust for this project?
If so can I get any simple example.

**Comment by Hywan** [comment]
Nothing I'm aware of. What do you want to know?

**Comment by AchalaSB** [comment]
i'm trying to run C code in go-wasmer. C code compiled in wasm using WASI
main.c
```
#include<stdio.h>
int main(int argc, char **argv)
{
  if (argc < 4) {
    printf("Hello, WASI!\n");
  } else {
    printf("Hello, %s!\n", argv[1]);
  }
}
```
main.go
```
package main

/*
#include<stdio.h>
#include<stdlib.h>
int main(int argc, char **argv)
{
  if (argc < 4) {
    printf("Hello, WASI!\n");
  } else {
    printf("Hello, %s!\n", argv[1]);
  }
}
*/
import "C"
import (
	"fmt"
	wasm "github.com/wasmerio/go-ext-wasm/wasmer"
)
func test(x int32) int32{
	return x
}

func main() {
	// Reads the WebAssembly module as bytes.
         bytes, _ := wasm.ReadBytes("/home/achala/codes/wasm-play/src/new.wasm")
	imports, _ := wasm.NewImports().Append("test", test, C.test)
	instance, err := wasm.NewInstanceWithImports(bytes, imports)
	if err != nil {
		panic(err)
	  }
	defer instance.Close()
	res := instance.Exports["main"]
	result, _ := res(2)
	fmt.Println(result) 
}
```
This is endup error
```
# command-line-arguments
./Ctest.go:29:55: could not determine kind of name for C.test
```
How can I call C/C++ code in go-wasmer ?

**Comment by Hywan** [comment]
Considering #92 is merged (it still a draft, it's blocked by https://github.com/wasmerio/wasmer/pull/1028 and https://github.com/wasmerio/wasmer/pull/1030, they are all landing very soon).

Let's consider the following C++ program:

```cpp
#include <stdio.h>

extern "C" {
  int32_t sum(int32_t, int32_t) __attribute__((used));
  int32_t sum(int32_t x, int32_t y) {
    return x + y;
  }
}

int main(int argc, char **argv) {
  if (argc < 2) {
    printf("Hello, WASI!\n");
  } else {
    printf("Hello, %s!\n", argv[1]);
  }
}
```

You can compile it with:

```sh
$ wasicc wasi_c.cpp -o wasi_c
```

Then from Go:

```go
module, err := wasm.Compile(getBytes("wasi_c.wasm"))
assert.NoError(t, err)

wasiVersion := wasm.WasiGetVersion(module)
assert.Equal(t, wasiVersion, wasm.Snapshot0)

importObject := wasm.NewDefaultWasiImportObjectForVersion(wasiVersion)

instance, err := module.InstantiateWithImportObject(importObject)
assert.NoError(t, err)

defer instance.Close()

// `_starts` calls the `main` function. It prints `Hello, WASI!`.
start, exists := instance.Exports["_start"]
assert.Equal(t, true, exists)

_, err = start()
assert.NoError(t, err)

// `sum` is a regular exported function.
sum, exists := instance.Exports["sum"]
assert.Equal(t, true, exists)

output, err := sum(1, 2)
assert.NoError(t, err)
assert.Equal(t, wasm.I32(3), output)
```

As soon as the PR mentionned above are merged, we have to wait for a new Wasmer release, and we will good to go!

Hope it helps.
