### ISSUE TITLE
Add support uint8, uint16, uint32, uint64 and []byte types

### ISSUE THREAD

**Issue by skillful-alex** [wasmerio/go-ext-wasm#78]
Thanks for proposing a new feature!

### Motivation

I would like to have support of all types, which are present at the same time in Wasm and Go. No I see error: only accept int32, int64, float32, and float64.

### Proposed solution

Change switches in `func (imports *Imports) Append` etc

**Comment by Hywan** [comment]
WebAssembly currently only supports int32, int64, float32 and float64. There is an effort to support more types with WIT ([WebAssembly Interface Types](https://github.com/WebAssembly/interface-types)), and we are actively working on it. Since then, you have to be patient :-).

**Comment by skillful-alex** [comment]
Well thank you.
Maybe for someone this link is useful:
http://webassembly.github.io/spec/core/syntax/types.html#syntax-valtype
> Integers are not inherently signed or unsigned, their interpretation is determined by individual operations.
