### ISSUE TITLE
Failed to run life benchmark with special wasm test file

### ISSUE THREAD

**Issue by dugusanfeng** [wasmerio/go-ext-wasm#79]
Thanks for the bug report!

### Describe the bug

Failed to run life benchmark with pollard_rho_128.wasm and snappy_compress.wasm file

### Steps to reproduce

1. Go to benchmarks dir
2. go test --bench=".*" -cpuprofile=cpu.profile ./life
3. error stack:
goos: linux
goarch: amd64
pkg: github.com/wasmerio/go-ext-wasm/benchmarks/life
Benchmark_Life_Nbody               	       1	3238359573 ns/op
Benchmark_Life_Fibonacci_Recursive 	       1	4683564409 ns/op
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x56215b]

goroutine 13 [running]:
github.com/perlin-network/life/exec.(*VirtualMachine).getExport(...)
	/home/steven/work/src/github.com/perlin-network/life/exec/vm.go:737
github.com/perlin-network/life/exec.(*VirtualMachine).GetFunctionExport(...)
	/home/steven/work/src/github.com/perlin-network/life/exec/vm.go:760
github.com/wasmerio/go-ext-wasm/benchmarks/life_test.benchmarkLife(0xc000072000, 0x5c0648, 0x14, 0x5bd597, 0x8, 0x0, 0x0, 0x0)
	/home/steven/work/src/github.com/wasmerio/go-ext-wasm/benchmarks/life/benchmarks_test.go:43 +0x18b
github.com/wasmerio/go-ext-wasm/benchmarks/life_test.Benchmark_Life_Pollard_Rho_128(0xc000072000)
	/home/steven/work/src/github.com/wasmerio/go-ext-wasm/benchmarks/life/benchmarks_test.go:31 +0x66
testing.(*B).runN(0xc000072000, 0x1)
	/usr/local/go/src/testing/benchmark.go:176 +0xb3
testing.(*B).run1.func1(0xc000072000)
	/usr/local/go/src/testing/benchmark.go:249 +0x5a
created by testing.(*B).run1
	/usr/local/go/src/testing/benchmark.go:242 +0x7d
exit status 2
FAIL	github.com/wasmerio/go-ext-wasm/benchmarks/life	8.176s

when I use perlin-network/life to run pollard_rho_128.wasm, it also throw error:
cmd: 
./life -entry 'app_main' ~/work/src/github.com/wasmerio/go-ext-wasm/wasmer/test/testdata/benchmarks/pollard_rho_128.wasm
error stack: 
panic: Error: inconsistent stack pattern: pt = false, lpt = false, ls = 1, sd = 0
---GO TRACEBACK---
goroutine 1 [running]:
runtime/debug.Stack(0x58bce0, 0xc000051180, 0x6312e0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/perlin-network/life/utils.CatchPanic(0xc000299aa0)
	/home/steven/work/wasm/life/utils/catch.go:11 +0x86
panic(0x58bce0, 0xc000051180)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/perlin-network/life/compiler.(*SSAFunctionCompiler).Compile(0xc0002999e8, 0xc000299800, 0x0, 0x0)
	/home/steven/work/wasm/life/compiler/ssa.go:336 +0xca45
github.com/perlin-network/life/compiler.(*Module).CompileForInterpreter(0xc00000e020, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/steven/work/wasm/life/compiler/module.go:237 +0xae8
github.com/perlin-network/life/exec.NewVirtualMachine(0xc00010a000, 0xcc859, 0xcca59, 0x0, 0x0, 0x0, 0x0, 0x0, 0x80, 0x10000, ...)
	/home/steven/work/wasm/life/exec/vm.go:437 +0xd0
main.main()
	/home/steven/work/wasm/life/main.go:82 +0x2f6

goroutine 1 [running]:
main.main()
	/home/steven/work/wasm/life/main.go:89 +0xbe6

**Comment by Hywan** [comment]
Thanks for the bug report,

Please use the `just bench` command, or unfold it:

https://github.com/wasmerio/go-ext-wasm/blob/e0517c02f18efb99cd29720fdb9cfbfbe3de650b/justfile#L48-L50

```sh
$ cd benchmarks/{{subject}} && go test -bench '{{filter}}' benchmarks_test.go
```

**Comment by Hywan** [comment]
I'm closing the issue for the moment, but feel free to re-open at any moment!
