### ISSUE TITLE
"bad magic number" from wasm blob built with Go

### ISSUE THREAD

**Issue by mjibson** [wasmerio/go-ext-wasm#81]
I have a small go file:

```
package w

func sum(x, y int) int {
	return x + y
}
```

I build it to a wasm blob:

```
GOOS=js GOARCH=wasm go build -o web.wasm w/w.go
```

But when running `wasmer.NewInstance` on it, I get:

```
Failed to instantiate the module:
    compile error: Validation error "Bad magic number"
```

Does go not build compatible wasm blobs?

**Comment by Hywan** [comment]
`wasm2wat` tells me the same. The resulting `web.wasm` file contains this:

```
!<arch>
__.PKGDEF       0           0     0     644     118       `
go object js wasm go1.12.8 X:framepointer
build id "f4e5LZ0A-5ohVijh4Sns/xwk6yYDmaERJ6X8P8yL1"


$$B
i

**Comment by Hywan** [comment]
I'm not sure Go can generate a WebAssembly module from a library only, it seems to work for a binary only.

I'm closing the issue since it's not related to this project, but feel free to re-open at any moment :-)!

**Comment by waynr** [comment]
For future explorers of the Wasm frontiers, I have gotten past this problem by compiling to wasm with [`tinygo`](https://tinygo.org/webassembly/webassembly/)

**Comment by Hywan** [comment]
Yup, tinygo seems a nice solution for this kind of usage.
