### ISSUE TITLE
How can we pass `String` or `str` data type in go-wasmer?

### ISSUE THREAD

**Issue by AchalaSB** [wasmerio/go-ext-wasm#86]
How can we pass String data types?
I could see this example, where we can pass it as a pointer. or we can use C_String (I'm not recommending this approach for my work)
```
 #[no_mangle]
pub extern fn string() -> *const u8 {
    b"Hello, World!\0".as_ptr()
}
```
 How can I pass `str` or `String` directly? 

Or How can we pass, one of the parameter as u8 array  and the return type as f64?
EX:
```
#[no_mangle]
pub extern fn test( b:f64, s:*const u8) -> f64 {
 match s {
  "x" => b * b,
   _ => 0
  }
}
```

Thanks,

**Comment by AdamSLevy** [comment]
Wasm modules only understand pointers to data within their memory. If you are passing a pointer into a Wasm Module's exported function, then it will need to be to some memory it can access. One way is to export a function within the module that will hand back a pointer that the host can write to. 

The Greet example demonstrates this:

Golang host code:
https://github.com/wasmerio/go-ext-wasm/blob/master/wasmer/example_greet_test.go

Rust/Wasm code:
https://github.com/wasmerio/go-ext-wasm/blob/master/wasmer/test/testdata/examples/greet.rs

**Comment by Hywan** [comment]
Sorry for the late reply, I missed your message!

Only i32, i64, f32, and f64 are supported for the moment. WIT (Interface Types) are coming inside Wasmer, but it's a long work (actually 99% of the work is done, I'm working on it).

So far, the `greet` example is the way you've to deal with it, as mentionned by @AdamSLevy.

**Comment by AchalaSB** [comment]
Hey @Hywan thanks for update. 
I was thinking about all the basic data types support including Strings, arrays, structs etc. 
Only way even i knew to pass it as pointers. checking out the way to pass not only as a memory pointers

So the WIT in this wasmer will support Arrays, Strings and struct??

**Comment by Hywan** [comment]
It is correct. _But_, WIT is still a large draft. Whilst Wasmer might support basic experimental support, I don't know if it's good for the users to spread this experimental feature in all language integrations (such as Go or Python for instance). Moreover, for the moment, no compiler emits WIT custom section (in the WebAssembly module), so it requires intermediate temporary tooling to get everything working. As I said, it is experimental and under heavy drafting.

**Comment by Hywan** [comment]
Closing the issue as @AdamSLevy has replied to the question. Please re-open if you need more inputs.

**Comment by Laisky** [comment]
These files are not exists now, I find a permanent link for this file: <https://github.com/wasmerio/wasmer-go/blob/75326bf847202945964e09905ecf64bd9d1baeee/wasmer/example_greet_test.go>


> Wasm modules only understand pointers to data within their memory. If you are passing a pointer into a Wasm Module's exported function, then it will need to be to some memory it can access. One way is to export a function within the module that will hand back a pointer that the host can write to.
> 
> The Greet example demonstrates this:
> 
> Golang host code: https://github.com/wasmerio/go-ext-wasm/blob/master/wasmer/example_greet_test.go
> 
> Rust/Wasm code: https://github.com/wasmerio/go-ext-wasm/blob/master/wasmer/test/testdata/examples/greet.rs
