### ISSUE TITLE
Running C++ exported functions from go-ext-wasm fails.

### ISSUE THREAD

**Issue by robinvanemden** [wasmerio/go-ext-wasm#91]
I am trying to call basic  "main()" functions in some c and cpp based wasms from go-ext-wasm:
    
```
...

result, err := instance.Exports["main"](1,1)
if err != nil { panic(err) }

...
```

But go-ext-wasm returns:

```
panic: Failed to call the `main` exported function.
```

Is there some way other way to run main()?

**Comment by robinvanemden** [comment]
It seems this problem is more generic then just calling main - the same panic is returned when calling any C++ function exported like so:

To run our C++ based framework, we need to invoke an exported function `pred()` in a WASI standalone Webassembly binary compiled using Emscripten. The main() and pred() functions are defined as follows in the cpp file:

```
extern "C" {
    int pred() __attribute__((used));
    int pred() {
        printf("Running pred()\n");
        double *prediction = cpwbart();
        double result = prediction[0] + mu;
        return (0);
    }
}

int main() {
    printf("Running main()\n");
    double *prediction = cpwbart();
    double result = prediction[0] + mu;
    return (0);
}

```
We call `pred()` as follows: 

```
	importObject := wasm.NewDefaultWasiImportObject()
	imports, err := importObject.Imports()
	if err != nil { panic(err) }

	err = importObject.Extend(*imports)
	if err != nil { panic(err) }

	bytes, err := wasm.ReadBytes("bart_snapshot1.wasm")
        if err != nil { panic(err) }

	module, err := wasm.Compile(bytes)
	if err != nil { panic(err) }

	instance, err := module.InstantiateWithImportObject(importObject)
	if err != nil { panic(err) }

	defer instance.Close()

	fmt.Println(instance.Exports); // pred is available in the exports

	message, err := instance.Exports["pred"]()
	if err != nil { panic(err) }        
       
        // result: panic: Failed to call the `pred` exported function.

```

Maybe related to the Wasmer issue here: https://github.com/wasmerio/wasmer/issues/1024 ?

**Comment by robinvanemden** [comment]
As I WASI ABI functions can now be invoked using https://github.com/wasmerio/wasmer/pull/1036, I also tried to call a WASI function from go-ext-wasm with a build based on that PR:

```
[dependencies]
wasmer-runtime-c-api = { git = "https://github.com/wasmerio/wasmer", branch = "feature/experimental-wasi-invoke" }
```

Yet the resulting go-ext-wasm lib with its new libwasmer_runtime_c_api.so still results in: 

```
result: panic: Failed to call the `pred` exported function.
```

So I expect there is still some go-ext-wasm specific issue at play? Or the way I seek to incorporate the Wasmer PR is off , that's certainly a possibility too!

**Comment by Hywan** [comment]
As @MarkMcCaskey said, I'm not sure it is expected to call an exported function with WASI. WASI expects one entry point, which is a `_start` function.

I tried the following:

```cpp
#include <stdio.h>

extern "C" {
  int hello() __attribute__((used));
  int hello() {
    printf("Hello from an exported function!");

    return 42;
  }
}


int main(int argc, char **argv)
{
  if (argc < 2) {
    printf("Hello, WASI!\n");
  } else {
    printf("Hello, %s!\n", argv[1]);
  }
}
```

Calling `_start` (i.e. `main`) works well, but calling `hello` correctly returns `42` (exactly `wasm.I32(42)`) but `Hello from an exported function!` isn't printed on stdout.

@MarkMcCaskey Any idea why?

**Comment by robinvanemden** [comment]
> As @MarkMcCaskey said, I'm not sure it is expected to call an exported function with WASI. WASI expects one entry point, which is a `_start` function.

I understand. But seeing that, for instance, Emscripten strongly moves towards a WASI ABI, it helps to be able to invoke other functions. And helps us easily interface with several machine learning libraries.

The exported function problem is indeed exactly what we encounter too - your example code works perfectly with the lastest Wasmer when hello is invoked through the cli, but not yet through go-ext-wasm.

Also, thanks again for all of the work you (and the Wasmer team) are putting in. It is much appreciated!

**Comment by robinvanemden** [comment]
> As @MarkMcCaskey said, I'm not sure it is expected to call an exported function with WASI. WASI expects one entry point, which is a `_start` function.

I do understand. Yet seeing that the WebAssembly ecosystem moves towards general use of the WASI ABI, it helps to be able to invoke other functions outside of `main()`.

> Hello from an exported function! isn't printed on stdout. 

Probably that's the result of the missing "\n", I expect this will work: 

`printf("Hello from an exported function!\n");`

I sought to replicate our own issue with a minimal example was well, as the issue we encounter differs from yours. Do let me know if you'd prefer it if I open a new issue for the following.

The C++ code to replicate our issue:

```
#include <stdio.h>
#include <string>

extern "C" {
int big_data_function() __attribute__((used));
int big_data_function() {
    std::string itv = R"~~~~(
    200 200 23
    3
    1 13 0 0
    2 0 0 15794.29427
    )~~~~";
    std::fwrite(itv.c_str(), 1, 50, stdout); // print first 50 bytes
    return (0);
}
}

int main(int argc, char **argv)
{
        printf("Hello, WASI!\n");
}
```

Compile with:

```
wasic++ -O3 test1.cpp -o test1.wasm
```

Then successfully run `test1.wasm` with the latest Wasmer CLI: 

```
> wasmer run test1.wasm -i big_data_function

WARNING: Invoking a function with WASI is not officially supported in the WASI standard yet.  Use this feature at your own risk, things may not work!

200 200 23
3
1 13 0 0
2 0 0 15794.29427
big_data_function returned [I32(0)]
```

But when running the same function from `go-ext-wasm` using the following code:

```
package main

import (
	"fmt"
	 wasm "github.com/wasmerio/go-ext-wasm/wasmer"
)
func main() {
	importObject := wasm.NewDefaultWasiImportObject()
	imports, err := importObject.Imports()
	if err != nil { panic(err) }

	err = importObject.Extend(*imports)
	if err != nil { panic(err) }

	bytes, err := wasm.ReadBytes("test1.wasm")
       if err != nil { panic(err) }

	module, err := wasm.Compile(bytes)
	if err != nil { panic(err) }

	instance, err := module.InstantiateWithImportObject(importObject)
	if err != nil { panic(err) }

	defer instance.Close()

	fmt.Println(instance.Exports);

	 message, err := instance.Exports["big_data_function"]()
	 if err != nil { panic(err) }

     fmt.Println(message)
}
```


for now still using the wasi_snapshot_preview1 workaround...

```
> wasm2wat test1.wasm > test1.wat  && sed -i 's/wasi_unstable/wasi_snapshot_preview1/g' test1.wat && wat2wasm test1.wat > test1.wasm
> go run test1.go
```

... Go panics with `Failed to call the `big_data_function` exported function`: 

```
map[_start:0x49cc80 big_data_function:0x49cc80]
panic: Failed to call the `big_data_function` exported function.

goroutine 1 [running]:
main.main()
        /mnt/c/Users/robin/CPPtest/test1.go:30 +0x3ab
exit status 2
```

I find it difficult to pinpoint the problem, it seems I am close, but not quite there yet. It does seems to have to do with invoking C++ functions and/or libs from go-ext-wasm. Basic C code works fine, generally.

**Comment by Hywan** [comment]
Can you check the exported function exists:

```go
big_data_function, exists := instance.Exports["big_data_function"]

if false == exists {
    panic("The exported function doesn't exist")
}

message, err := big_data_function()

// …
```

**Comment by robinvanemden** [comment]
Sure! When I do the following:

```
   ...
	fmt.Println(instance.Exports);

	big_data_function, exists := instance.Exports["big_data_function"]

        if false == exists {
            panic("The exported function doesn't exist")
        } else {
            fmt.Println("Exported function *exists*")
        }

        fmt.Println(big_data_function)
    ...
```

I get:

```
map[_start:0x49cc80 big_data_function:0x49cc80]
Exported function *exists*
0x49cc80
```

Followed, of course, by, the `panic: Failed to call the 'big_data_function' exported function.` later on in the code.
`
If I can help out in any other way, just let me know!

**Comment by robinvanemden** [comment]
It seems I was looking in the wrong direction: the panic did not result from any C or C++ code related issues. It was my own Go code all along. Specifically, some leftover code from extending the import object in an earlier version of our module:

```
        importObject := wasm.NewDefaultWasiImportObject()
	imports, _ := importObject.Imports()  
	importObject.Extend(*imports)
        instance, _ := module.InstantiateWithImportObject(importObject)
```

That messed up the import object. So changing it into: 

```
        importObject := wasm.NewDefaultWasiImportObject()
        instance, _ := module.InstantiateWithImportObject(importObject)
```

... solved the issue. As always, thanks for your support and feedback!

**Comment by robinvanemden** [comment]
Also, exported functions do indeed not seem to print to stdout, either with or without trailing '\n' - don't know what is happening there.

**Comment by Hywan** [comment]
Closing the issue since the initial problem is solved :-). We are looking at the other issue.
